
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/linuxbrew/.linuxbrew/Cellar/cmake/3.27.2/share/cmake/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.1.44-060144-generic - x86_64
...
